services:
  - type: web
    name: discord-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        fromSecret: true
      - key: ROLE_ID
        fromSecret: true
      - key: CHANNEL_ID
        fromSecret: true
